name: minitrivia_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  serverpod: 2.0.0-alpha.1

dev_dependencies:
  lints: ^3.0.0
